# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.3.dev1+g07d6b85.d20220719'
__version_tuple__ = version_tuple = (0, 3, 'dev1', 'g07d6b85.d20220719')
