package:
  name: "lyceanem"
  version: "0.0.1"
about:
  summary: "LyceanEM is a Python library for modelling electromagnetic propagation for sensors and communications. You can find the documentation at https://lyceanem-python.readthedocs.io/en/latest/"

source:
  path: ..

build:
  noarch: python
  script: python setup.py install