package:
  name: lyceanem
  version: {{ GIT_DESCRIBE_TAG }}
source:
  path: ..


build:
  script_env:
    - CMAKE_GENERATOR=Ninja
requirements:
  build:
  - python                    # from defaults or conda-forge
  - pip                       # from defaults or conda-forge
  - git
  - conda-forge::numpy
  - conda-forge::pybind11
  - conda-forge::cmake
  - conda-forge::ninja
  - conda-forge::scikit-build
  - {{ compiler('cxx') }}

  # NVIDIA components to build CUDA code (no full runtime)
  - nvidia::cuda-nvcc
  - nvidia::cuda-cudart-dev
  - nvidia::cuda-cudart-static
  host:
  - python
  - libboost-python-devel
  - nvidia::cuda-cudart-dev
  - nvidia::cuda-cudart-static
  - pip                       # from defaults or conda-forge
  - conda-forge::numpy
  - conda-forge::pybind11
  - conda-forge::cmake
  - conda-forge::ninja
  - conda-forge::scikit-build
  - nvidia::cuda-nvcc

#  - conda-forge::cxx-compiler

  # NVIDIA components to build CUDA code (no full runtime)
  - nvidia::cuda-nvcc
  - nvidia::cuda-cudart-dev
  - nvidia::cuda-cudart-static

  run:

    - python
    - conda-forge::numpy
    - conda-forge::scipy
    - conda-forge::numba
    - conda-forge::numba-cuda
    - conda-forge::cudatoolkit
    - conda-forge::cupy
    - conda-forge::importlib_resources
    - conda-forge::meshio
    - conda-forge::pyvista>=0.45
    - conda-forge::python-gmsh



about:
  home: https://documentation.lyceanem.com/en/latest/
  summary: >
    LyceanEM is a Python library for modelling electromagnetic propagation
    for sensors and communications. You can find the documentation at
    https://documentation.lyceanem.com/en/latest/
  license: GPL-3.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - LyceanEM

test:
  imports:
    - lyceanem
    - lyceanem.em

  commands:
    - python -c "from lyceanem.em import bin_counts_to_numpy; print('bin_counts_to_numpy import successful')"
    - python -c "from lyceanem.em import bin_triangles_to_numpy; print('bin_triangles_to_numpy import successful')"
    - python -c "from lyceanem.em import calculate_scattering_brute_force; print('calculate_scattering_brute_force import successful')"
    - python -c "from lyceanem.em import calculate_scattering_tiles; print('calculate_scattering_tiles import successful')"
