name: PyPI - Manual Publish

on:
  workflow_dispatch:     # Only manual trigger
    branches:
      - master

permissions:
  contents: read

jobs:
    publish:
      name: Publish to PyPI
      runs-on: ubuntu-latest
      environment: pypi   # recommended: create this environment in GitHub repo settings
      permissions:
        id-token: write   # mandatory for trusted publishing

      steps:
        - uses: actions/checkout@v4

        - name: Download all built wheels
          uses: actions/download-artifact@v4
          with:
            path: wheelhouse
            pattern: lyceanem-wheels-*
            merge-multiple: true

        - name: Publish to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            packages-dir: wheelhouse